# Generated by Django 6.0.2 on 2026-02-12 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tress', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='treedonation',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='treedonation',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='treedonation',
            name='is_user_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='treedonation',
            name='user_deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
