# Generated by Django 6.0.2 on 2026-02-12 07:53

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tress', '0002_treedonation_approval_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treedonation',
            name='plantation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='treedonation',
            name='plantation_update',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='treedonation',
            name='planted_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='treedonation',
            name='planted_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='treedonation',
            name='planted_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='treedonation',
            name='proof_image_1',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='treedonation',
            name='proof_image_2',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='treedonation',
            name='thank_you_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='treedonation',
            name='trees_planted_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
