# Generated by Django 6.0.2 on 2026-02-12 10:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tress', '0003_treedonation_plantation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treedonation',
            name='tracking_token',
            field=models.CharField(db_index=True, default=uuid.uuid4, editable=False, max_length=40),
        ),
    ]
